apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: pinpoint-mysql
  name: pinpoint-mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pinpoint-mysql
    spec:
      containers:
      - image: 'private.docker.hub:5000/pinpointdocker/pinpoint-mysql:1.8.1'
        name: pinpoint-mysql
        env:
          - name: MYSQL_DATABASE
            #value: pinpoint
            valueFrom:
             configMapKeyRef:
               name: pinpoint-env
               key: MYSQL_DATABASE
          - name: MYSQL_PASSWORD
            #value: admin
            valueFrom:
             configMapKeyRef:
               name: pinpoint-env
               key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            #value: root123
            valueFrom:
             configMapKeyRef:
              name: pinpoint-env
              key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            #value: admin
            valueFrom:
             configMapKeyRef:
              name: pinpoint-env
              key: MYSQL_USER
        ports:
          - containerPort: 3306
        resources: {}
        volumeMounts:
          #- mountPath: /var/lib/mysql
          #  name: mysql-data
      restartPolicy: Always
      volumes:
      #- name: mysql-data
      #  emptyDir: {} 
status: {}
