apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: pinpoint-quickstart
  name: pinpoint-quickstart
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pinpoint-quickstart
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -javaagent:/pinpoint-agent/pinpoint-bootstrap-1.8.1.jar -Dpinpoint.agentId=pinpoint-quickstart -Dpinpoint.applicationName=pinpoint-quickstart
        image: private.docker.hub:5000/pinpointdocker/pinpoint-quickstart:v1.8.1
        imagePullPolicy: Always
        name: pinpoint-quickstart
        ports:
        - containerPort: 8080
        resources: {}
        #volumeMounts:
        #- mountPath: /pinpoint-agent
        #  name: data-volume
      restartPolicy: Always
      #volumes:
      #- name: data-volume
      #  emptyDir: {}
status: {}
