apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: pinpoint-hbase
  name: pinpoint-hbase
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pinpoint-hbase
    spec:
      containers:
      - image: 'private.docker.hub:5000/pinpointdocker/pinpoint-hbase:1.8.1'
        #imagePullPolicy: Always
        name: pinpoint-hbase
        #${BASE_DIR}/hbase-${HBASE_VERSION}/bin/hbase master start
        #command:
        #  - "/opt/hbase/hbase-1.2.6/bin/hbase"
        #args:
        #  - "master"
        #  - "start"
        #环境变量
        env:
          - name: HBASE_ZOOKEEPER_QUORUM
            value: zoo1, zoo2, zoo3
        ports:
        - containerPort: 2181
        - containerPort: 60000
        - containerPort: 16010
        - containerPort: 60020
        - containerPort: 16030
        resources: {}
        volumeMounts:
        #- mountPath: /home/pinpoint/hbase
        #  name: pinpoint-hbase-claim0
        #- mountPath: /home/pinpoint/zookeeper
        #  name: pinpoint-hbase-claim1
        - name: config-volume
          mountPath: /etc/config
      restartPolicy: Always
      volumes:
      #- name: pinpoint-hbase-claim0
      #  emptyDir: {}
      #- name: pinpoint-hbase-claim1
      #  emptyDir: {}
      - name: config-volume
        configMap:
          name: pinpoint-config
          items:
            - key: "pinpoint-config.yaml"
              path: "pinpoint-config.yaml" 
status: {}
