apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: pinpoint-collector
  name: pinpoint-collector
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pinpoint-collector
    spec:
      containers:
      - name: pinpoint-collector
        env:
         - name: CLUSTER_ENABLE
           value: "true"
         - name: CLUSTER_ZOOKEEPER_ADDRESS
           value: zoo1
         - name: DEBUG_LEVEL
           value: INFO
         - name: FLINK_CLUSTER_ENABLE
           value: "true"
         - name: FLINK_CLUSTER_ZOOKEEPER_ADDRESS
           value: zoo1
         - name: HBASE_HOST
           value: pinpoint-hbase
         - name: HBASE_PORT
           value: "2181"
        image: 'private.docker.hub:5000/pinpointdocker/pinpoint-collector:1.8.1'       
        ports:
        - containerPort: 9994
        - containerPort: 9995
          protocol: UDP
        - containerPort: 9996
          protocol: UDP
        resources: {}
      restartPolicy: Always
status: {}
