#:apiVersion: extensions/v1beta1
#kind: Deployment
apiVersion: apps/v1
kind: Deployment
#kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: pinpoint-collector
  name: pinpoint-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pinpoint-collector
  #strategy: {}
  #serviceName: pinpoint-collector
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pinpoint-collector
    spec:
      containers:
      - name: pinpoint-collector
        env:
         - name: CLUSTER_ENABLE
           #value: "false"
           valueFrom:
            configMapKeyRef:
              name: pinpoint-env
              key: CLUSTER_ENABLE
         - name: CLUSTER_ZOOKEEPER_ADDRESS
           #value: "zoo1"
           valueFrom:
            configMapKeyRef:
              name: pinpoint-env
              key: CLUSTER_ZOOKEEPER_ADDRESS
         - name: DEBUG_LEVEL
           #value: INFO
           valueFrom:
            configMapKeyRef:
              name: pinpoint-env
              key: DEBUG_LEVEL
         - name: FLINK_CLUSTER_ENABLE
           #value: "false"
           valueFrom:
            configMapKeyRef:
              name: pinpoint-env
              key: FLINK_CLUSTER_ENABLE
         - name: FLINK_CLUSTER_ZOOKEEPER_ADDRESS
           #value: "zoo1"
           valueFrom:
            configMapKeyRef:
              name: pinpoint-env
              key: FLINK_CLUSTER_ZOOKEEPER_ADDRESS
         - name: HBASE_HOST
           #value: "pinpoint-hbase"
           valueFrom:
            configMapKeyRef:
              name: pinpoint-env
              key: HBASE_HOST
         - name: HBASE_PORT
           #value: "2181"
           valueFrom:
            configMapKeyRef:
              name: pinpoint-env
              key: HBASE_PORT
        image: 'private.docker.hub:5000/pinpointdocker/pinpoint-collector:1.8.1'       
        ports:
        - containerPort: 9994
        - containerPort: 9995
          protocol: UDP
        - containerPort: 9996
          protocol: UDP
        resources: {}
      restartPolicy: Always
status: {}
